// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MontageAPI.Data;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MontageAPI.Data.ProjectObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ProjectObjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "г. Москва, Лиговский пр-т, д. 30А",
                            Name = "ТЦ «Галерея» — 3 этаж",
                            Status = "В работе"
                        },
                        new
                        {
                            Id = 2,
                            Address = "г. Москва, Пресненская наб., д. 12",
                            Name = "Офисный центр «Сити Плаза»",
                            Status = "В работе"
                        },
                        new
                        {
                            Id = 3,
                            Address = "г. Подольск, ул. Индустриальная, д. 45",
                            Name = "Складской комплекс «Логистик»",
                            Status = "Новый"
                        },
                        new
                        {
                            Id = 4,
                            Address = "г. Химки, ул. Молодежная, д. 78",
                            Name = "ЖК «Солнечный» — Корпус 5",
                            Status = "Завершен"
                        },
                        new
                        {
                            Id = 5,
                            Address = "г. Котельники, мкр. Белая Дача, д. 35",
                            Name = "Ресторан «Белая Дача»",
                            Status = "В работе"
                        });
                });

            modelBuilder.Entity("MontageAPI.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Админ Админыч",
                            Login = "admin",
                            PasswordHash = "$2a$11$dc1VxlASa9fsQ33sus.lLeABXBYn.p5XeLFC00.DYJr6bIe8wesdi",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Иванов Д.Д.",
                            Login = "worker1",
                            PasswordHash = "$2a$11$..WwhVyRJ01jvphb1KjViuC7OpnYWN6UcqUFH6zr3o1XbIpUTnmGi",
                            Role = "Worker"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Сидоров И.Д.",
                            Login = "worker2",
                            PasswordHash = "$2a$11$WdQpOz794/D36vGVJo2S3uxLJ4wuk9DZVRN5rR2LJf5yN2mzIac.2",
                            Role = "Worker"
                        });
                });

            modelBuilder.Entity("MontageAPI.Data.UserObjectAssignment", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ObjectId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ObjectId");

                    b.HasIndex("ObjectId");

                    b.ToTable("UserObjectAssignments");

                    b.HasData(
                        new
                        {
                            UserId = 2,
                            ObjectId = 1
                        },
                        new
                        {
                            UserId = 2,
                            ObjectId = 2
                        },
                        new
                        {
                            UserId = 2,
                            ObjectId = 3
                        },
                        new
                        {
                            UserId = 3,
                            ObjectId = 3
                        },
                        new
                        {
                            UserId = 3,
                            ObjectId = 4
                        },
                        new
                        {
                            UserId = 3,
                            ObjectId = 5
                        });
                });

            modelBuilder.Entity("MontageAPI.Data.WorkReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ObjectId")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerUnit")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("WorkTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkTypeId");

                    b.HasIndex("ObjectId", "WorkDate");

                    b.HasIndex("UserId", "WorkDate");

                    b.ToTable("WorkReports");
                });

            modelBuilder.Entity("MontageAPI.Data.WorkType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("PricePerUnit")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Subtype")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Type", "Subtype");

                    b.ToTable("WorkTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Устройство (сверление) сквозных отверстий в стенах из кирпича, железобетонных перекрытиях, сенгвиче, сенгвич-панелях, металлических конструкциях прочих перегородках и стеновых конструкциях диаметром до 22 мм, глубиной до 1м, на высоте до 4м.",
                            PricePerUnit = 150.00m,
                            SortOrder = 1,
                            Subtype = "Отверстия",
                            Type = "Сверление, штробление и подрозетники",
                            Unit = "шт"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Устройство (сверление) сквозных отверстий в стенах из кирпича, железобетонных перекрытиях, сенгвиче, сенгвич-панелях, прочих перегородках и стеновых конструкциях диаметром до 42 мм, глубиной до 1м, на высоте до 4м.",
                            PricePerUnit = 250.00m,
                            SortOrder = 2,
                            Subtype = "Отверстия",
                            Type = "Сверление, штробление и подрозетники",
                            Unit = "шт"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Устройство (сверление) сквозных отверстий в стенах из кирпича, железобетонных перекрытиях, сенгвиче, сенгвич-панелях, прочих перегородках и стеновых конструкциях диаметром до 65 мм, глубиной до 380мм, на высоте до 4м.",
                            PricePerUnit = 400.00m,
                            SortOrder = 3,
                            Subtype = "Отверстия",
                            Type = "Сверление, штробление и подрозетники",
                            Unit = "шт"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Устройство (сверление) сквозных отверстий в металлических конструкциях (швелерах, метал. листах, лотках, крышках, профлистах, перегородках, существующих электрощитах, коммутационных щкафах) диаметром до 25 мм, глубиной до 6мм, на высоте до 4м.",
                            PricePerUnit = 200.00m,
                            SortOrder = 4,
                            Subtype = "Отверстия",
                            Type = "Сверление, штробление и подрозетники",
                            Unit = "шт"
                        });
                });

            modelBuilder.Entity("MontageAPI.Data.UserObjectAssignment", b =>
                {
                    b.HasOne("MontageAPI.Data.ProjectObject", "Object")
                        .WithMany("Assignments")
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MontageAPI.Data.User", "User")
                        .WithMany("Assignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Object");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MontageAPI.Data.WorkReport", b =>
                {
                    b.HasOne("MontageAPI.Data.ProjectObject", "Object")
                        .WithMany()
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MontageAPI.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MontageAPI.Data.WorkType", "WorkType")
                        .WithMany()
                        .HasForeignKey("WorkTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Object");

                    b.Navigation("User");

                    b.Navigation("WorkType");
                });

            modelBuilder.Entity("MontageAPI.Data.ProjectObject", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("MontageAPI.Data.User", b =>
                {
                    b.Navigation("Assignments");
                });
#pragma warning restore 612, 618
        }
    }
}
